### ISSUE TITLE
Does not work in Ubuntu 21.04

### ISSUE THREAD

**Issue by hkiang01** [bjarosze/gnome-bluetooth-quick-connect#38] opened 2021-06-20 03:42 UTC

**Comment by fugkco** [comment] 2021-06-30 04:03
Works fine here on Pop!_OS! You should post some more info on what exactly isn't working so the extension author is actually able to debug the issue.

**Comment by bjarosze** [comment] 2021-08-31 08:25
I need more info.

You can check if bluetoothctl is working: https://github.com/bjarosze/gnome-bluetooth-quick-connect#connecting-and-disconnecting-does-not-work

And send me some logs, e.g: 
```
journalctl -b `which gnome-shell` | grep -B 10 -A 10  bluetooth-quick-connect
```

**Comment by radek-sprta** [comment] 2021-08-31 18:55
I dug in deeper and the problem is not in the extension itself, but somewhere else. The extension was not enabled, even though all the other ones I installed were (the same way and on multiple machines too).

Anyway, since my problem is resolved and the OP is likely not posting any more details, I think you can close this issue.

**Closed** 2021-09-01 08:05 UTC
